modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"

[[mods]]
modId="sophimarket"
version="2.0.0"
displayName="SophiMarket V2"
description='''Market, métiers, récompenses et quêtes journalières pour Minecraft 1.21.1.'''

[[dependencies.sophimarket]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.sophimarket]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="BOTH"
